sonar.projectKey=cerami-craft
sonar.sources=app,src,components
sonar.exclusions=coverage/**/*,node_modules/**/*,**/*.html,**/*.xml,.expo/**/*
sonar.coverage.reportPaths=coverage/coverage-final.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
