sonar.organization=sw5005-sus
sonar.projectKey=cerami-craft
sonar.projectName=cerami-craft
sonar.sources=app,src,components
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/coverage/**,**/node_modules/**,**/dist/**,**/__tests__/**,**/*.html,**/*.xml,.expo/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
